Work in progress to add elm-analyse like diagnostics using tree-sitter
elm-tooling/elm-language-server pull request #322
Opened 2020-09-27 13:03 UTC by jmbockhorst

Had some fun using tree-sitter queries to start implementing some elm-analyse functionality. Currently, there is diagnostics for unsused import value and type, and unused import alias. Still working on more, just wanted to show the progress and how powerful using queries are.

2020-09-27 13:25 UTC, Razzeee commented on src/util/refactorEditUtils.ts
>        const exposedValues = TreeUtils.descendantsOfType(
Might want to rename this

2020-10-07 04:32 UTC, jmbockhorst commented
@Razzeee I added the list of checks that elm-analyse does and which ones I have implemented so far. Let me know or edit the list if there are some that you don't want to bring over. We can discuss, but I feel like there are some that we won't want to implement.

2020-10-07 07:04 UTC, Razzeee commented
Agreed, I would however not try to do all in one PR, so that list might be best moved to an issue.

2020-10-13 13:20 UTC, Razzeee commented on .github/workflows/npm-publish.yml
> -# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
Probably a rebase error

2020-10-13 13:52 UTC, jmbockhorst commented on .github/workflows/npm-publish.yml
> -# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
Then again, I'm not quite sure.

2020-10-16 13:57 UTC, jmbockhorst commented
Ready for review. All of the tests from elm-analyse pass, but there could still be wrong cases out there. I left elm-analyse in place so that we can do some manual testing and compare the diagnostics. Once we feel it is good enough, we can disable these when elm-analyse is on, or just remove elm-analyse all together.

Of course we can now do much more than elm-analyse ever did, but as a start, I want to implement it a close to the existing behavior. 

Feel free to change/reword the diagnostics messages.

2020-10-17 12:49 UTC, Razzeee commented
Great work, I will hopefully find some time next week to look at this, this weekend is pretty stuffed :)

2020-10-17 23:35 UTC, Razzeee requested changes

2020-10-17 23:35 UTC, Razzeee commented on src/providers/diagnostics/fileDiagnostics.ts
> +  Elm,
I'm conflicted on this name, might make more sense to name/report this as ElmLS? What do you think?

2020-10-17 23:36 UTC, jmbockhorst commented on src/providers/diagnostics/fileDiagnostics.ts
> +  Elm,
Yeah I didn't know what to name it. I'm fine with ElmLS.

2020-11-11 00:30 UTC, Razzeee commented on src/providers/diagnostics/elmDiagnostics.ts
> +        ...this.getUnusedImportDiagnostics(tree),
This is fine for now, but I think we will need at least the path ignore from here in the long run https://stil4m.github.io/elm-analyse/#/configuration

2020-11-11 01:02 UTC, Razzeee commented
Those changes, a rebase and a global on/off switch and we're good to go.

2020-11-11 04:56 UTC, jmbockhorst commented
Should be good now. Added a watch for the configuration so it updates dynamically.

2020-11-11 11:30 UTC, Razzeee commented on test/diagnosticTests/elmDiagnostics.test.ts
>  import { getSourceFiles } from "../utils/sourceParser";
This file should be renamed

2020-11-11 11:38 UTC, merged