Fix some type inference bugs
elm-tooling/elm-language-server pull request #349
Opened 2020-10-29 17:33 UTC by jmbockhorst

Found some inference bugs while working on using type inference to show compiler diagnostics.

2020-10-29 23:34 UTC, Razzeee commented
Seems to conflict, are there any test cases we should add?

2020-10-31 10:02 UTC, Razzeee requested changes
Looks good otherwise

2020-11-01 21:16 UTC, jmbockhorst commented
Ready to merge.

2020-11-01 21:56 UTC, Razzeee commented on src/util/treeUtils.ts
> +      .filter(Utils.notUndefined)
Is there a reason your removing this?

2020-11-02 00:12 UTC, jmbockhorst commented on src/util/treeUtils.ts
> +      .filter(Utils.notUndefined)
No, sorry probably happened in the merge.

2020-11-03 00:28 UTC, Razzeee commented on src/util/treeUtils.ts
> +      .filter(Utils.notUndefined)
Readded

2020-11-05 08:32 UTC, merged