Add github action to test diagnostics
elm-tooling/elm-language-server pull request #385
Opened 2020-12-03 12:31 UTC by jmbockhorst

This should give a "Run Manually" button on the actions tab. We could also set it up on a 24 hour schedule.

2020-12-03 17:01 UTC, Razzeee commented
The reason to not have this on the normal build is due to it taking too long?

2020-12-03 17:06 UTC, jmbockhorst commented
Yes. I'm running it now on my personal repo and it's been going for over 2 hours. It might be froze up because I can't see the logs.
https://github.com/jmbockhorst/elm-language-server/runs/1493270378?check_suite_focus=true

We can see, but I would suspect that even if it ran smooth it would take at least 30 minutes to an hour, or possibly more. Didn't think we'd want that on every push, but we can consider.

2020-12-04 00:28 UTC, Razzeee commented
Yeah, was just wondering what too long is in this case :)

2020-12-04 00:51 UTC, jmbockhorst commented
Actually, it looks like it just keeps getting stuck. Otherwise it should complete in 11-12 minutes.

2020-12-05 16:24 UTC, jmbockhorst commented
This is ready to go now. Currently it doesn’t fail when a library fails so that we can test them. We can enable that once they are all passing or we have a known failures list.  Unfortunately it looks like there are about 150 failures, which is way more than I saw last week. I will be looking at the workspaces invididually over the next week trying to find the issues.

2020-12-05 17:36 UTC, Razzeee commented on test/diagnostics.ts
> +        console.log(a);
Do you want to keep it like this?

2020-12-05 17:38 UTC, Razzeee commented on test/diagnostics.ts
> +    console.log();
Empty log?

2020-12-05 17:40 UTC, Razzeee commented on test/diagnostics.ts
> +      // !compilerFailures.includes(lib) &&
should these still be commented out? should we remove the variables?

2020-12-05 17:42 UTC, Razzeee requested changes
Some cleanup might be needed

2020-12-05 17:44 UTC, jmbockhorst commented on test/diagnostics.ts
> +      // !compilerFailures.includes(lib) &&
Going to re add them once we figure out which ones are actually parser or compile errors

2020-12-05 17:45 UTC, jmbockhorst commented on test/diagnostics.ts
> +        console.log(a);
Yeah I think it’ll help if there are any errors.

2020-12-05 17:45 UTC, jmbockhorst commented on test/diagnostics.ts
> +    console.log();
Just to add a space.

2020-12-06 00:57 UTC, merged