Adopt file events APIs
elm-tooling/elm-language-server pull request #409
Opened 2020-12-16 14:13 UTC by jmbockhorst

2020-12-19 18:12 UTC, Razzeee commented on src/elmWorkspace.ts
> +    ].find((elmFolder) => uri.includes(elmFolder));
Why includes? Shouldn't startsWith be better?

2020-12-19 18:25 UTC, jmbockhorst commented on src/elmWorkspace.ts
> +    ].find((elmFolder) => uri.includes(elmFolder));
At some point there was a case that needed this, but I don't remember. I can check again to see if it's still needed.

2020-12-19 18:31 UTC, Razzeee commented on src/util/types/typeChecker.ts
> +import { node } from "execa";
Seems unused

2020-12-19 18:59 UTC, Razzeee commented on test/definitionProviderTests/moduleResolveDefinition.test.ts
> +      --^Module/Model.elm
This is confusing to me, can you double check if it's correct, I will try to do the same.

2020-12-19 19:12 UTC, Razzeee commented on src/providers/renameProvider.ts
> +    // Adjust the case of Module.App.func
I think this comment could be better? `Helps us to rename fully qualified functions without changing the last part`

2020-12-19 19:17 UTC, jmbockhorst commented on test/definitionProviderTests/moduleResolveDefinition.test.ts
> +      --^Module/Model.elm
I changed the behavior to be like this. Since it doesn't make any sense in this context to navigate to a module named `Module`, which may or may not exist (if it doesn't, it navigates to `func`, which also doesn't make sense), it now takes the entire module name `Module.Model` when getting the definition. This was to improve renames, so it will consistently rename the the entire module `Module.Model` if the cursor is in either part.

2020-12-19 19:20 UTC, Razzeee commented on test/definitionProviderTests/moduleResolveDefinition.test.ts
> +      --^Module/Model.elm
But why is the `--X` unmoved? Shouldn't the test fail?

2020-12-19 20:07 UTC, jmbockhorst commented on test/definitionProviderTests/moduleResolveDefinition.test.ts
> +      --^Module/Model.elm
Hmm your right. I think it’s because the —X just determines a Position, not the source file. In this case the position is the same still.

2020-12-19 21:52 UTC, Razzeee commented on src/providers/handlers/fileEventsHandler.ts
> +    sourceFile,
I think we should mark sourceFile as optional in IParams

2020-12-19 22:00 UTC, Razzeee commented on src/providers/handlers/fileEventsHandler.ts
> +    file: string,
I think we would normally have called this uri?

2020-12-19 22:31 UTC, Razzeee commented on test/renameProvider.test.ts
> +    const renameRange = Range.create(
Seems like intelliJ-elm does this via {-carret-} which is nice, but not sure why they do it like that. The reference implementation in the rust world also does the same.

Can't think of good reasons, it might be a bit clearer where the cursor is, as we end up always pointing at a char, but the cursor in the real case will be between chars.
A good reason for us might be to reuse tests from intelliJ, but it's only 12 tests anyway.

https://github.com/klazuka/intellij-elm/blob/master/src/test/kotlin/org/elm/ide/refactoring/ElmRenameTest.kt
https://github.com/intellij-rust/intellij-rust/blob/master/src/test/kotlin/org/rust/ide/refactoring/RenameTest.kt

2020-12-19 22:34 UTC, Razzeee commented on test/renameProvider.test.ts
> +    await testRename(source, newName, [
It would be much nicer to not have to write a text edit and just compare the strings that end up in each file?

See the implementation in the intelliJ repo. They basically hand over a string for a file with a {-caret-} and a string how it's expected to look after renaming.

2020-12-19 22:37 UTC, Razzeee commented on test/renameProvider.test.ts
> +    await testRename(source, newName, [
I guess that might be a problem, whenever we want to test if renames in multiple files were successful.

2020-12-19 22:38 UTC, Razzeee commented on src/elmWorkspace.ts
> +    ].find((elmFolder) => uri.includes(elmFolder));
Please do :)

2020-12-19 22:39 UTC, Razzeee requested changes
Some minors in the implementation, but I think we can still improve the tests.

2020-12-19 22:43 UTC, Razzeee commented on test/definitionProviderTests/moduleResolveDefinition.test.ts
> +      --^Module/Model.elm
Yeah, it's right by mistake :/

2020-12-19 22:45 UTC, jmbockhorst commented on test/renameProvider.test.ts
> +    await testRename(source, newName, [
I was thinking this too, just didn't get to it. But I guess we need some way to apply text edits to a the string sources. Unless something exists that is easier, we'll probably have to convert our sources to line/col buffers and grab what vscode does to apply edits.

2020-12-19 23:09 UTC, Razzeee commented on test/renameProvider.test.ts
> +    await testRename(source, newName, [
Your right, I was hoping that we somehow could use `this.connection.workspace.applyEdit` but seems unlikely. I guess it's fine to create an issue from this and move on.

2020-12-20 00:01 UTC, Razzeee commented on src/providers/handlers/fileEventsHandler.ts
> +    sourceFile,
Seems to be a bigger refactor, probably something for later

2020-12-20 01:37 UTC, jmbockhorst commented on src/providers/handlers/fileEventsHandler.ts
> +    sourceFile,
Yeah, I’d rather not, because it will almost only exist.

2020-12-20 05:56 UTC, jmbockhorst commented on test/renameProvider.test.ts
> +    const renameRange = Range.create(
Well this range is the expected range of the rename, not just the caret position.

2020-12-20 06:04 UTC, jmbockhorst commented on test/renameProvider.test.ts
> +    await testRename(source, newName, [
Was able to add a simple implementation that applies code edits. Certainly room for improvement in the future but it works for now.

2020-12-20 06:05 UTC, jmbockhorst commented on src/elmWorkspace.ts
> +    ].find((elmFolder) => uri.includes(elmFolder));
I changed it back and it seems to be fine. Only tested manually on MacOS though. Since the tests are passing on Windows, I'm fairly confident it should be fine.

2020-12-20 06:07 UTC, jmbockhorst commented
With the new `applyEditsToSource`, in the future we should be able to easily add tests for code actions fairly easily.

2020-12-20 13:29 UTC, merged

2020-12-20 13:29 UTC, Razzeee commented
Thanks 🎉