Add code action for unused top level function
elm-tooling/elm-language-server pull request #540
Opened 2021-03-02 00:10 UTC by Razzeee

2021-03-03 12:57 UTC, jmbockhorst requested changes
Needs to remove doc comments as well. Other than like looks good.

2021-03-03 22:58 UTC, Razzeee commented
Great catch, should be fixed now

2021-03-04 00:17 UTC, Razzeee commented
Rebased and integrated with the new unused code

2021-03-04 02:59 UTC, jmbockhorst approved these changes

2021-03-04 07:47 UTC, merged