Removes 'Unused Value Constructor' errors on modules that expose all of their contents
elm-tooling/elm-language-server pull request #544
Opened 2021-03-04 08:50 UTC by MixmasterFresh

Before this commit, `elmLsDiagnostics` doesn't present the 'Unused Value Constructor' warning for modules that either use the Value somewhere(correct) or expose the parent type explicitly with the '(..)' operator to expose the variants(this is speculative because the type may not be used elsewhere even though it's exported). This change just expands that logic to also include cases where the module implicitly exposes the parent type and its variants, by using the '(..)' indicator to expose all contents of the module. 

Ideally this and the other speculative case should be removed in favor of a solution that considers whether the variants are actually used in other files, but this is something that I am not familiar enough with the codebase to do quite yet. However, the tests have been modified to prepare for such a solution and a test has been added to test the multiple file variant usage case, but in the meantime, that test also tests the single file 'expose all' case.

I'm personally much more in favor of considering multiple files for this warning, so if that's not a gargantuan effort, please point me in that direction and I'll create that pull request instead.

2021-03-04 19:03 UTC, jmbockhorst requested changes
We don't currently check other files for any of the unused diagnostics. We have planned to do that but we just haven't gotten to it yet.

2021-03-05 00:47 UTC, MixmasterFresh commented on src/providers/diagnostics/elmLsDiagnostics.ts
> +      .matches(tree.rootNode)
As best I can tell(and I may be off with this) the parser is weirdly inconsistent/incorrect with `moduleDeclaration` when there is a comment in the first line(which is the normal formatting of these tests, and is valid elm as far as I'm aware). I'm getting that module definition parsed as type `ERROR`, but that node has a child with type `module_declaration`. This would also mean that, by extension, `TreeUtils.findModuleDeclaration` is also incorrect, since it is just using `tree.rootNode.childForFieldName("moduleDeclaration")`

2021-03-05 00:51 UTC, jmbockhorst commented on src/providers/diagnostics/elmLsDiagnostics.ts
> +      .matches(tree.rootNode)
The first comment shouldn't be parsed in the test. Or if it is, that is a problem.

2021-03-05 01:05 UTC, MixmasterFresh commented on src/providers/diagnostics/elmLsDiagnostics.ts
> +      .matches(tree.rootNode)
I'm about 70% sure it is. If I'm understanding it correctly, [this line](https://github.com/elm-tooling/elm-language-server/blob/808c50999442e39d86d116606d013847d721903a/test/utils/sourceParser.ts#L256) is saving the filename comment as the beginning of the file when we split it into sources.

I can also confirm that starting the file with a comment is valid elm(in so far as the compiler doesn't complain when I do it, whether or not that's the intention) which means that starting with a comment shouldn't really matter to the parser here.

2021-03-05 01:13 UTC, jmbockhorst commented on src/providers/diagnostics/elmLsDiagnostics.ts
> +      .matches(tree.rootNode)
Yeah, so maybe we need to fix our parser.

2021-03-05 01:14 UTC, MixmasterFresh commented on src/providers/diagnostics/elmLsDiagnostics.ts
> +      .matches(tree.rootNode)
If I wanted to do that, could you point me in that direction?

2021-03-05 01:27 UTC, Razzeee commented on src/providers/diagnostics/elmLsDiagnostics.ts
> +      .matches(tree.rootNode)
Just checked, there are no comments filename/starting (--@Bla.elm) comments in `sources`. So we should be fine. But it does have some stray spaces.

![image](https://user-images.githubusercontent.com/5943908/110053767-439fb200-7d5a-11eb-8397-2945757a45fc.png)

2021-03-05 01:30 UTC, MixmasterFresh commented on src/providers/diagnostics/elmLsDiagnostics.ts
> +      .matches(tree.rootNode)
Weird, so what do you think would be causing the `ERROR` node? I'm well out of my depth here

2021-03-05 01:31 UTC, Razzeee commented on src/providers/diagnostics/elmLsDiagnostics.ts
> +      .matches(tree.rootNode)
Can you create a failing test with that case or when does it happen for you?

2021-03-05 01:35 UTC, MixmasterFresh commented on src/providers/diagnostics/elmLsDiagnostics.ts
> +      .matches(tree.rootNode)
The test case I added in this PR hits it. I only realized it because I tried to add the code that @jmbockhorst suggested(which should work) and was getting `undefined` for the module declaration.

2021-03-05 01:51 UTC, Razzeee commented on test/diagnosticTests/elmLsDiagnostics.test.ts
> +      --@ Main.elm
The indentation here is probably your problem.

My testing had this for e.g.:
```
module Main exposing (..)

      import B exposing (C(..))

      f : Int -> C
      f x =
          if x > 1 then
              Something
          else
              SomethingElse

```

Just remove the leading spaces from each line :)

2021-03-05 01:53 UTC, Razzeee commented on test/diagnosticTests/elmLsDiagnostics.test.ts
> +      --@ Main.elm
Btw, totally our fault for not doing it smarter.

2021-03-05 02:25 UTC, MixmasterFresh commented on test/diagnosticTests/elmLsDiagnostics.test.ts
> +      --@ Main.elm
Oh wow, that's a much easier fix. Thanks for the assist.

2021-03-05 02:35 UTC, MixmasterFresh commented on src/providers/diagnostics/elmLsDiagnostics.ts
> +      .matches(tree.rootNode)
This is now resolved as I added the code that @jmbockhorst suggested(with the addition of optional chaining for null safety). Thanks for the help!

2021-03-05 04:42 UTC, jmbockhorst approved these changes
Looks good to me. Thanks!

2021-03-05 08:39 UTC, Razzeee commented
Thanks for working on this 🎉

2021-03-05 08:39 UTC, merged