Add a code action to add missing union constructors
elm-tooling/elm-language-server pull request #628
Opened 2021-08-30 03:28 UTC by jmbockhorst

Closes #476.

2021-08-30 13:18 UTC, razzeee commented
Tests seem unhappy

2021-08-31 02:30 UTC, jmbockhorst commented
Whoops, I changed the name at the last minute. Still not sure about union variant/type/constructor naming.

2021-08-31 08:46 UTC, razzeee requested changes
Just some minors, looks good otherwise

2021-08-31 12:19 UTC, jmbockhorst commented on src/util/refactorEditUtils.ts
> +        `\n${spaces}| ${name}${params.length > 0 ? " " : ""}${params
When `params === 0` there is still a `name`, so it will be line `| NewMsg`. Params is just the part after that.

2021-08-31 12:34 UTC, razzeee approved these changes

2021-08-31 12:34 UTC, merged