Fix for reference count of function in a let, with a type annotation.
elm-tooling/elm-language-server pull request #691
Opened 2022-05-05 23:13 UTC by jbuedel

This fixes a bug where values in a `let...in` have a zero reference count, if they have a type annotation.

This gif demonstrates the problem. Watch how the count changes from 2 to 0 depending on the presence of the type annotation. 
![image](https://user-images.githubusercontent.com/85681/167041621-b294a22f-75df-42a3-9780-025a66700666.png)

2022-05-06 12:43 UTC, jmbockhorst requested changes
Just a few minor changes. Also, it would be great if you could write a simple test in `functionDefinition.test.ts`.

2022-05-06 12:43 UTC, jmbockhorst commented on src/compiler/typeChecker.ts
> +        nodeAtPosition.parent?.nextNamedSibling?.type === "value_declaration"
`nodeAtPosition.parent?` can be replaced with `nodeParent`, for a small perf improvement. Same for below.

2022-05-06 12:43 UTC, jmbockhorst commented on src/compiler/typeChecker.ts
> +            name: nodeAtPosition.text,
Replace `nodeAtPosition.text` with `nodeText`.

2022-05-10 07:08 UTC, razzeee commented
This needs formatting with prettier. Should this then still be a draft?

2022-05-10 16:52 UTC, jbuedel commented
> This needs formatting with prettier. Should this then still be a draft?

Hey @razzeee I don't understand. Are you suggesting I take it out of draft mode until the formatting is corrected? I put it in draft mode to indicate I was still working on it. (Which includes adding that unit test, formatting, and whatever else comes up.)

2022-05-10 17:12 UTC, razzeee commented
Keep it in draft, if you want to keep working on it. Sometimes people forget to change it :)

2022-05-20 20:23 UTC, jbuedel commented
@razzeee It seems that my unit test is not actually even calling the bug fix code that I added. Am I interpreting this correctly?

2022-05-21 00:33 UTC, razzeee commented
Yes, your code is not reached. It seems like it's due to the first `--X` changing the code/tree in some significant way.

2022-11-05 23:48 UTC, razzeee commented
We know this fixes the problem. I've just retested it.

I've removed the test now, as it's not proving that's the case, as the added comment below the type annotation seems to change the parsed tree and thus invalidates the test.

2022-11-06 17:56 UTC, merged